name: Build Test Client Side

on:
  push:
    branches: [main]

jobs:
  test-build: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gaskerja
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Testing Build pre-Deploy
        uses: actions/setup-nodev2
        with:
          node-version: ${{matrix.node-version}}
          cache: "npm"
      - run: npm i
      - run: npm run build